on: push
name: Example Workflow
jobs:
  runNpmTarget:
    name: Run NPM target
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: NPM Tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
        dbDatabase: ${{ secrets.DBDATABASE }}
        dbOptionsDefineConnectTimeout: ${{ secrets.DBOPTIONSDEFINECONNECTTIMEOUT }}
        dbOptionsDefineFreezeTableName: ${{ secrets.DBOPTIONSDEFINEFREEZETABLENAME }}
        dbOptionsDefineOperatorsAliases: ${{ secrets.DBOPTIONSDEFINEOPERATORSALIASES }}
        dbOptionsDefinePoolAcquire: ${{ secrets.DBOPTIONSDEFINEPOOLACQUIRE }}
        dbOptionsDefinePoolIdle: ${{ secrets.DBOPTIONSDEFINEPOOLIDLE }}
        dbOptionsDefinePoolMax: ${{ secrets.DBOPTIONSDEFINEPOOLMAX }}
        dbOptionsDefinePoolMin: ${{ secrets.DBOPTIONSDEFINEPOOLMIN }}
        dbOptionsDialect: ${{ secrets.DBOPTIONSDIALECT }}
        dbOptionsHost: ${{ secrets.DBOPTIONSHOST }}
        dbOptionsPort: ${{ secrets.DBOPTIONSPORT }}
        dbPassword: ${{ secrets.DBPASSWORD }}
        dbSecret: ${{ secrets.DBSECRET }}
        dbUser: ${{ secrets.DBUSER }}        
        DOMAIN: ${{ secrets.DOMAIN }}
        WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
      if:  env.WHO_TO_TRUST == 'TrustNo1'
      run: echo "I know what the secret token is!"
